
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const ExpenseDashboardPage = lazy(() => import("./pages/ExpenseDashboardPage.tsx"));
const ExpenseSheetDetailPage = lazy(() => import("./pages/ExpenseSheetDetailPage.tsx"));
const FirebaseSignInPage = lazy(() => import("./pages/FirebaseSignInPage.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const UserProfilePage = lazy(() => import("./pages/UserProfilePage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/expense-dashboard-page", element: <UserGuard><ExpenseDashboardPage /></UserGuard>},
	{ path: "/expensedashboardpage", element: <UserGuard><ExpenseDashboardPage /></UserGuard>},
	{ path: "/expense-sheet-detail-page", element: <UserGuard><ExpenseSheetDetailPage /></UserGuard>},
	{ path: "/expensesheetdetailpage", element: <UserGuard><ExpenseSheetDetailPage /></UserGuard>},
	{ path: "/firebase-sign-in-page", element: <FirebaseSignInPage />},
	{ path: "/firebasesigninpage", element: <FirebaseSignInPage />},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/user-profile-page", element: <UserGuard><UserProfilePage /></UserGuard>},
	{ path: "/userprofilepage", element: <UserGuard><UserProfilePage /></UserGuard>},

];
